ASPMVCTestAPP/Models/Bike.cs
namespace ASPMVCTestAPP.Models
{
    public class Bike
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public string Model { get; set; }

        public int MaxSpeed { get; set; }
    }
}

ASPMVCTestAPP/Models/ErrorViewModel.cs
namespace ASPMVCTestAPP.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ASPMVCTestAPP/Controllers/BikeController.cs
using ASPMVCTestAPP.Models;
using ASPMVCTestAPP.Services;
using Microsoft.AspNetCore.Mvc;

namespace ASPMVCTestAPP.Controllers
{
    public class BikeController : Controller
    {
        BikeService bikeService;

        public BikeController()
        {
            bikeService = new BikeService();
        }
        public IActionResult Index()
        {

            List<Bike> bikes = bikeService.GetBikes();
            return View(bikes);
        }

        public IActionResult AddBike(Bike bike)
        {

            bikeService.AddBike(bike);
            return View();
        }

    }
}

ASPMVCTestAPP/Controllers/HomeController.cs
using ASPMVCTestAPP.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ASPMVCTestAPP.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASPMVCTestAPP/Views/Bike/AddBike.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Bike

@{
}

ASPMVCTestAPP/Views/Bike/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model List<Bike>


@{
}
<div class="text-center">
    <h1 class="display-4">Welcome to Bike</h1>
    <table>
        <thead>
            <tr>
                <td>Bike ID</td>
                <td>Name</td>
                <td>Max Speed</td>
                <td>Model</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var bike in Model)
            {
                <tr>
                    <td>@bike.Id</td>
                    <td>@bike.Name</td>
                    <td>@bike.MaxSpeed</td>
                    <td>@bike.Model</td>
                </tr>
            }
        </tbody>
    </table>
</div>

ASPMVCTestAPP/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ASPMVCTestAPP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASPMVCTestAPP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASPMVCTestAPP.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASPMVCTestAPP</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bike" asp-action="Index">Bike</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ASPMVCTestAPP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>